import detailedSeatingChart from '@/lib/seating-chart-config.json';
import { Event } from '@/lib/types';

export const sampleEvents: Omit<Event, 'id'>[] = [
  {
    name: 'Starlight Symphony Orchestra',
    description: 'An enchanting evening with the Starlight Symphony Orchestra, performing timeless classics under the stars. A must-see for music lovers.',
    category: 'Music',
    date: new Date(new Date().setDate(new Date().getDate() + 7)).toISOString(),
    location: 'Jaipur, Rajasthan',
    venue: 'RIC Auditorium',
    image: 'https://picsum.photos/seed/event1/600/400',
    showtimes: ['19:00', '21:30'],
    ticketTypes: [{ type: 'Standard', price: 299 }],
    seatingChart: detailedSeatingChart as any
  },
  {
    name: 'Tech Visionaries Summit 2024',
    description: 'Join industry leaders and innovators for a day of insightful talks on the future of technology, AI, and sustainability.',
    category: 'Seminar',
    date: new Date(new Date().setDate(new Date().getDate() + 14)).toISOString(),
    location: 'Jaipur, Rajasthan',
    venue: 'Convention Hall',
    image: 'https://picsum.photos/seed/event2/600/400',
    showtimes: ['09:00', '11:00', '14:00'],
    ticketTypes: [{ type: 'Standard', price: 99 }],
    seatingChart: detailedSeatingChart as any
  },
  {
    name: 'Abstract Realities: A Modern Art Exhibit',
    description: 'Explore the vibrant and thought-provoking world of modern abstract art from renowned artists across the globe.',
    category: 'Art',
    date: new Date(new Date().setDate(new Date().getDate() + 21)).toISOString(),
    location: 'Jaipur, Rajasthan',
    venue: 'Art Gallery',
    image: 'https://picsum.photos/seed/event3/600/400',
    showtimes: ['10:00 - 18:00'],
    ticketTypes: [{ type: 'Standard', price: 0 }],
  },
   {
    name: 'Hamlet: A Contemporary Tragedy',
    description: "Experience Shakespeare's masterpiece like never before in this gripping, modern-day adaptation of the classic tragedy.",
    category: 'Theater',
    date: new Date(new Date().setDate(new Date().getDate() + 30)).toISOString(),
    location: 'Jaipur, Rajasthan',
    venue: 'Main Auditorium',
    image: 'https://picsum.photos/seed/event4/600/400',
    showtimes: ['20:00'],
    ticketTypes: [{ type: 'Standard', price: 499 }],
    seatingChart: detailedSeatingChart as any
  },
  {
    name: 'Global Rhythms: A Cultural Dance Festival',
    description: 'Celebrate the diversity of world cultures through the universal language of dance. Featuring troupes from five continents.',
    category: 'Cultural',
    date: new Date(new Date().setDate(new Date().getDate() + 45)).toISOString(),
    location: 'Jaipur, Rajasthan',
    venue: 'Open Air Theatre',
    image: 'https://picsum.photos/seed/event5/600/400',
    showtimes: ['18:30'],
    ticketTypes: [{ type: 'Standard', price: 199 }],
     seatingChart: detailedSeatingChart as any
  },
];

export const sampleMembers = [
  {
    applicationId: 1001,
    memberId: 1,
    categoryType: "Individual",
    categoryAcronym: "IND",
    doa: "2023-01-15T00:00:00.000Z",
    name: "John Doe",
    phone: "+91 9876543210",
    email: "john.doe@example.com",
    dob: "1985-05-20T00:00:00.000Z",
    address: "123 Main St, Jaipur, Rajasthan",
    emergencyContact: "+91 9876543211",
  },
  {
    applicationId: 1002,
    memberId: 2,
    categoryType: "Corporate",
    categoryAcronym: "CORP",
    doa: "2023-02-10T00:00:00.000Z",
    name: "Jane Smith",
    phone: "+91 8765432109",
    email: "jane.smith@example.com",
    dob: "1990-08-15T00:00:00.000Z",
    address: "456 Corporate Ave, Jaipur, Rajasthan",
    emergencyContact: "+91 8765432108",
  },
  {
    applicationId: 1003,
    memberId: 3,
    categoryType: "Student",
    categoryAcronym: "STU",
    doa: "2023-03-05T00:00:00.000Z",
    name: "Alice Johnson",
    phone: "+91 7654321098",
    email: "alice.j@example.com",
    dob: "2000-11-10T00:00:00.000Z",
    address: "789 University Rd, Jaipur, Rajasthan",
    emergencyContact: "+91 7654321097",
  },
  {
    applicationId: 1004,
    memberId: 4,
    categoryType: "Senior Citizen",
    categoryAcronym: "SEN",
    doa: "2022-11-20T00:00:00.000Z",
    name: "Robert Williams",
    phone: "+91 6543210987",
    email: "robert.w@example.com",
    dob: "1950-02-25T00:00:00.000Z",
    address: "321 Quiet Lane, Jaipur, Rajasthan",
    emergencyContact: "+91 6543210986",
  },
  {
    applicationId: 1005,
    memberId: 5,
    categoryType: "Individual",
    categoryAcronym: "IND",
    doa: "2023-05-12T00:00:00.000Z",
    name: "Emily Brown",
    phone: "+91 5432109876",
    email: "emily.b@example.com",
    dob: "1992-07-30T00:00:00.000Z",
    address: "654 Elm St, Jaipur, Rajasthan",
    emergencyContact: "+91 5432109875",
  }
];
